<div id="rect">
    <div class="col-md-6 bounceright" align="center">
        <img src="/img/man2.png" class="prof-pict">
    </div>
    <div class="col-md-6 bounceright">
        
        <label class="aboutme">Hi I'm Charlie a Developer</label>
        <p class="paragraf">Halo, undanganku! Saya seorang developer berpengalaman dalam pembuatan undangan digital pada website. 
            Saya sangat bersemangat untuk dapat membantu Anda membuat undangan digital yang sesuai dengan keinginan dan kebutuhan Anda. 
            Sebagai seorang developer, saya memiliki pengetahuan dan keterampilan yang diperlukan untuk menciptakan desain undangan digital yang menarik dan profesional. 
            Saya dapat mengintegrasikan elemen-elemen desain seperti teks, gambar, video, dan grafik ke dalam undangan digital Anda. 
            Selain itu, saya juga bisa mengoptimalkan undangan digital Anda dengan fitur-fitur yang interaktif.</p>
    </div>
</div>
   


    <script>
$( document ).ready(function() {
    // console.log( "ready!" );

	});
  
</script>